// components/ContactComponent.tsx
import React from 'react'
import Image from 'next/image'

type Props = {}

export default function ContactComponent({ }: Props) {
  return (
    <div className='flex flex-row'>
      <div>
        <div className='text-3xl font-bold'>For more information or to arrange a tour, contact Chris Parrott</div>
        <div>

        </div>
      </div>
      <Image src='/./../public/contact-image.png' width={430} height={143} alt='Portrait of our travel agent Chris' />
    </div>
  )
}

// src/app/pages/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  template: ` <br />
    <h2
      id="contact"
      class="xl:hidden text-xl text-center font-semibold mt-10 mx-4"
    >
      For more information or to arrange a tour, contact Chris Parrott
    </h2>
    <div class="xl:flex xl:flex-row-reverse">
      <img
        src="./../../../assets/contact-image.png"
        alt="Portrait of Chris"
        class="h-56 mx-auto my-5 xl:h-96"
      />
      <div class="xl:my-auto xl:w-2/3">
        <h2
          id="contact"
          class="hidden xl:flex text-3xl w-2/3 mx-auto text-center my-2"
        >
          For more information or to arrange a tour, contact Chris Parrott
        </h2>
        <ul class="flex flex-col mx-4 xl:text-2xl xl:mx-40">
          <li class="mx-auto xl:mx-0">
            <b>Email: </b>
            <a
              href="mailto:chris@chrisparrot.ca"
              class="text-blue-800 underline"
              >chris&#64;chrisparrot.ca</a
            >
          </li>
          <li class="mx-auto xl:mx-0"><b>Phone: </b>306-206-0383</li>
          <li class="mx-auto xl:mx-0">
            <b>Cell: </b> <a href="tel:306-206-0383">306-537-6447</a>
          </li>
          <li class="mx-auto xl:mx-0"><b>Fax: </b> 306-206-0383</li>
          <li class="mx-auto md:mx-auto xl:mx-auto">
            <b>Address: </b> #3 1118 Broad Street. Realty One Real Estate
            Services Inc. Regina, SK. S4R 1X8
          </li>
        </ul>
      </div>
    </div>`,
  styleUrls: ['./contact.component.css'],
})
export class ContactComponent {}

<br>
<h2 id="contact" class="xl:hidden text-xl text-center font-semibold mt-10 mx-4">For more information or to arrange a
  tour, contact
  Chris
  Parrott
</h2>
<div class="xl:flex xl:flex-row-reverse">
  <img src="./../../../assets/contact-image.png" alt="Portrait of Chris" class="h-56 mx-auto my-5 xl:h-96">
  <div class="xl:my-auto xl:w-2/3">

    <h2 id="contact" class="hidden xl:flex text-3xl w-2/3 mx-auto text-center my-2">For more information or to arrange a
      tour,
      contact
      Chris
      Parrott
    </h2>
    <ul class="flex flex-col mx-4 xl:text-2xl xl:mx-40">
      <li class="mx-auto xl:mx-0 "><b>Email: </b> <a href="mailto:chris@chrisparrot.ca">chris&#64;chrisparrot.ca</a></li>
      <li class="mx-auto xl:mx-0 "><b>Phone: </b>306-206-0383</li>
      <li class="mx-auto xl:mx-0 "><b>Cell: </b> <a href="tel:306-206-0383">306-537-6447</a></li>
      <li class="mx-auto xl:mx-0 "><b>Fax: </b> 306-206-0383</li>
      <li class="mx-auto md:mx-20 xl:mx-0 "><b>Address: </b> #3 1118 Broad Street.
        Realty One Real Estate Services Inc.
        Regina, SK. S4R 1X8</li>
    </ul>
  </div>
</div>
